### ISSUE TITLE
Dashboard Page Wireframe

### ISSUE THREAD

**Issue by Rohit-Mundada** [Devsoc-BPGC/pmt-frontend#7]
**What is required?**
To make components for the main dashboard page which will be shown after logging in with GitHub. It consists of a side bar with frequently navigable links like "Calendar", "Statistics", "Profile", etc. It will consist of a list of project boards (much like Trello) and a place to put all the recent bugs/issues related to all the ongoing projects. 
The dashboard page also includes a collapsible side navigation for going to different chat channels of projects.

[Link to Wireframes](https://www.figma.com/file/kn72x5RW2eAozXhOPiVMq2/Wireframes?node-id=0%3A1)

**Comment by Rohit-Mundada** [comment]
I am doing component 1.
(Sidebar pane for navigation)

**Comment by Yash-g17** [comment]
I'm gonna do component 6.
(Notification Dropdown)

**Comment by Rohit-Mundada** [comment]
> I am doing component 1.
> (Sidebar pane for navigation)

(Basic layout done, but i have hardcoded values for now)

**Comment by Taarushthenoob** [comment]
Rohit, make the top navbar heading a prop so it can be reused in Taskboard. Components 6 and 7 will also be reused in the Taskboard

**Comment by Rohit-Mundada** [comment]
> Rohit, make the top navbar heading a prop so it can be reused in Taskboard. Components 6 and 7 will also be reused in the Taskboard

Yes I have made it a separate component.

**Comment by Aviral09** [comment]
I am taking up component 3.
(Project Cards + Add new Project button)

**Comment by resonantChaos22** [comment]
I will do component 4 (task board cards + button)
